name: CI

on:
  push:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    name: build-artifact
    
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: '0'
      
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.36.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
        id: auto_tagger
      
      - name: Setup Go environment
        uses: actions/setup-go@v3.2.0
        with:
          go-version-file: ./go.mod
      
      - name: Build
        run: |
          go version
          go build 
          ls -la

      - name: Tag release w/ artifact
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          automatic_release_tag: ${{ steps.auto_tagger.outputs.new_tag }}
          files: |
            perccli-prom
          

